port: 9091
logs_level: info
jwt_secret: insecure_secret
authentication_backend:
  file:
    path: /etc/authelia/users.yml
totp:
  issuer: example.com
session:
  secret: samplesecret
  domain: example.com
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
storage:
  local:
    path: /var/lib/authelia/db.sqlite
access_control:
  default_policy: deny
  rules:
    - domain: "public.example.com"
      policy: bypass
    - domain: "traefik.example.com"
      policy: one_factor
